// Regenerates src/data/*.ts from the committed source files in data/.
//   node scripts/gen-data.mjs
// Update data/kody_bank_CR.csv by downloading it again from ČNB and adjust
// BANK_CODES_META below (retrieval date and the server's Last-Modified date).
import { readFileSync, writeFileSync } from "node:fs";

const BANK_CODES_META = {
  source: "https://www.cnb.cz/cs/platebni-styk/.galleries/ucty_kody_bank/download/kody_bank_CR.csv",
  page: "https://www.cnb.cz/cs/platebni-styk/ucty-kody-bank/",
  retrieved: "2026-10-09",
  lastModified: "2026-09-25",
};

const root = new URL("../", import.meta.url);
const header = "// Generated by scripts/gen-data.mjs. Do not edit by hand.\n";

// --- ČNB bank codes -------------------------------------------------------
const csv = readFileSync(new URL("data/kody_bank_CR.csv", root), "utf8").replace(/^\uFEFF/, "");
const rows = csv.split(/\r?\n/).filter((l) => l.trim() !== "");
const head = rows.shift();
if (!head?.startsWith("Kód platebního styku;")) throw new Error(`Unexpected CSV header: ${head}`);
const banks = rows.map((line) => {
  const cols = line.split(";").map((c) => c.trim());
  if (cols.length !== 4 || !/^\d{4}$/.test(cols[0])) throw new Error(`Unexpected CSV row: ${line}`);
  const [code, name, bic, certis] = cols;
  return [code, name, bic === "" ? null : bic, certis === "A"];
});
banks.sort((a, b) => (a[0] < b[0] ? -1 : 1));
writeFileSync(
  new URL("src/data/bank-codes.ts", root),
  `${header}// Source: Czech National Bank, "Kódy bank / platebního styku" (${BANK_CODES_META.page}).\n` +
    `\n/** Where and when the bundled bank-code list was obtained. */\nexport const BANK_CODES_META = ${JSON.stringify(BANK_CODES_META, null, 2)} as const;\n\n` +
    `/** @internal [code, name, BIC or null, CERTIS participant] */\nexport const BANK_CODE_ROWS: ReadonlyArray<readonly [string, string, string | null, boolean]> = [\n` +
    banks.map((b) => `  ${JSON.stringify(b)},`).join("\n") +
    `\n];\n`,
);

// --- IBAN registry --------------------------------------------------------
const reg = readFileSync(new URL("data/iban-registry.txt", root), "utf8")
  .split("\n")
  .filter((l) => l !== "" && !l.startsWith("#"))
  .map((l) => {
    const m = /^([A-Z]{2}) (\d+) ((?:\d+![nac])+) (.+)$/.exec(l);
    if (!m) throw new Error(`Unexpected registry row: ${l}`);
    const [, cc, len, bban, name] = m;
    const sum = [...bban.matchAll(/(\d+)!/g)].reduce((s, x) => s + Number(x[1]), 0);
    if (sum + 4 !== Number(len)) throw new Error(`Length mismatch for ${cc}`);
    return [cc, Number(len), bban, name];
  });
writeFileSync(
  new URL("src/data/iban-registry.ts", root),
  `${header}// Source: SWIFT IBAN Registry release 101 (see data/iban-registry.txt for provenance).\n\n` +
    `/** @internal [country, IBAN length, BBAN structure, country name] */\nexport const IBAN_REGISTRY_ROWS: ReadonlyArray<readonly [string, number, string, string]> = [\n` +
    reg.map((r) => `  ${JSON.stringify(r)},`).join("\n") +
    `\n];\n`,
);
console.log(`bank codes: ${banks.length}, IBAN countries: ${reg.length}`);
